kind: MLApp
metadata:
  name: caffe2
spec:
  package_manager: "pip2"
  packages:
    - names:
      {{- range $i, $value := .packages }}
      - "{{ $value }}"
      {{- end }}
      manager: "pip2"
  tasks:
  - name: prepare-data
    resources:
    - name: upload
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 1
      allowFail: true
      images:
        cpu: busybox
      command: "echo \"Uploading Data\";echo \"Done!!!\""
      workdir: "$DATA_DIR"
      volumes:
      - name: data
  - name: standalone
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: true
      images:
        gpu: "kuberlab/mlboard-jupyter-caffe2:{{.caffe2_version.value}}-gpu-py2"
        cpu: "kuberlab/mlboard-jupyter-caffe2:{{.caffe2_version.value}}-cpu-py2"
      command: "python2 hello.py"
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 0
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 1000m
          memory: 4Gi
      default_volume_mapping: true
  uix:
  - name: jupyter
    displayName: Jupyter
    images:
      gpu: "kuberlab/mlboard-jupyter-caffe2:{{.caffe2_version.value}}-gpu-py2"
      cpu: "kuberlab/mlboard-jupyter-caffe2:{{.caffe2_version.value}}-cpu-py2"
    resources:
      accelerators:
        gpu: 0
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 4Gi
    ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    default_volume_mapping: true
  serving:
  - name: serving
    displayName: Serving
    images:
      gpu: "kuberlab/mlboard-jupyter-caffe2:{{.caffe2_version.value}}-gpu-py2"
      cpu: "kuberlab/mlboard-jupyter-caffe2:{{.caffe2_version.value}}-cpu-py2"
    workdir: "$SRC_DIR"
    command: "python hello.py"
    resources:
      accelerators:
        gpu: 0
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 4Gi
    ports:
    - port: {{ .serving_port }}
      targetPort: {{ .serving_port }}
      protocol: TCP
      name: http
    default_volume_mapping: true
  volumes:
  - isLibDir: false
    mountPath: /notebooks/training
    name: training
    clusterStorage: {{ .storage.value }}
    subPath: training
  - gitRepo:
      repository: https://github.com/kuberlab-catalog/caffe2-mlapp
    isLibDir: false
    mountPath: /notebooks/src
    name: src
    subPath: caffe2-mlapp/src
  - isLibDir: true
    mountPath: /notebooks/lib
    name: lib
    clusterStorage: {{ .storage.value }}
    subPath: lib
  - isLibDir: false
    mountPath: /notebooks/data
    name: data
    clusterStorage: {{ .storage.value }}
    subPath: {{ .data_path }}
  - isLibDir: false
    mountPath: /notebooks
    name: code
    subPath: code
    clusterStorage: {{ .storage.value }}
