storage: 
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage
src: 
 value: https://github.com/kuberlab-catalog/caffe2-mlapp
 wizard:
  name: "Code source"
  kind: git
src_path: /caffe2-mlapp/src
data_path: data
tensorflow_version: 1.2.0
python_version:
  value: "2"
  wizard:
    name: "Python version"
    kind: select
    options:
    - "2"
    - "3"
serving_port: 9000
tf_serving: false
packages:
 - "git+https://github.com/kuberlab/python-mlboardclient.git"
